### ISSUE TITLE
error 111 'Connection refused

### ISSUE THREAD

**Issue by mancuniancol** [romanvm/kodi.yatp#10]
HI Roman, I have some addon and script that it could use YATP to play the torrents links.

It was working perfect, but I've noticed an error this week and the YATP stops to work

13:31:10 T:139771842123520  NOTICE: -->Python Interpreter Initialized<--
13:31:11 T:139771842123520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', error(111, 'Connection refused'))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.yatp/main.py", line 12, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/simpleplugin.py", line 486, in run
                                                result = action_callable(params)
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/client/actions.py", line 78, in play_torrent
                                                return _play(buffer_torrent(params['torrent'], file_index))
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/client/buffering.py", line 122, in buffer_torrent
                                                torrent_data = add_torrent(torrent)
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/client/buffering.py", line 46, in add_torrent
                                                jsonrq.add_torrent(torrent)
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/client/json_requests.py", line 32, in add_torrent
                                                _request({'method': 'add_torrent', 'params': {'torrent': torrent}})
                                              File "/storage/.kodi/addons/plugin.video.yatp/libs/client/json_requests.py", line 24, in _request
                                                reply = post(json_rpc_url, json=data).json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 109, in post
                                                return request('post', url, data=data, json=json, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 50, in request
                                                response = session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 465, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 573, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 415, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
                                            -->End of Python script error report<--
13:31:11 T:139773690730368   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.yatp/?action=play&torrent=magnet%3A%3Fxt%3Durn%3Abtih%3Aoapnrkkimuutjwygsm42s2vh2cefi3fo%26tr%3Dhttp%3A%2F%2Fopen.nyaatorrents.info%3A6544%2Fannounce%26tr%3Dudp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce]

I've rechecked the documentation, and it seems that I am calling YATP correctly.  Any help will be appreciated

**Comment by romanvm** [comment]
Please provide a full Kodi debug log with LibCurl logging enabled.

**Comment by mancuniancol** [comment]
Thank you for your answer. I've done some test, I've found out that it was a conflict between two version from requests.  I did again a clean install, but this time I only allow your requests version to install and now, the problem is fixed.  Sorry, to waste your time :(
